language: php

sudo: false

cache:
    directories:
        - $HOME/.composer/cache

php:
    - 7.0
    - 7.1
    - hhvm
    - nightly

before_install:
    - composer self-update

install:
    - composer install

script:
    - phpunit

matrix:
    fast_finish: true
    include:
        - php: 7.0
        - php: 7.1
    allow_failures:
        - php: hhvm
        - php: nightly

notifications:
    email: false
