language: php

sudo: false

cache:
    directories:
        - $HOME/.composer/cache

php:
    - 7.0
    - 7.1
    - hhvm
    - nightly

before_install:
    - if [ "$TRAVIS_PHP_VERSION" != "hhvm" ]; then phpenv rehash; fi;
    - composer self-update
    - if [ "$SYMFONY_VERSION" != "" ]; then composer require "symfony/symfony:${SYMFONY_VERSION}" --no-update; fi;

install:
    - composer install

script:
    - phpunit

matrix:
    fast_finish: true
    include:
        - php: 7.0
          env: SYMFONY_VERSION=3.2.*
        - php: 7.0
          env: SYMFONY_VERSION=3.2.*
        - php: 7.0
          env: SYMFONY_VERSION=3.2.*
        - php: 7.1
          env: SYMFONY_VERSION=3.0.*
        - php: 7.1
          env: SYMFONY_VERSION=3.2.*
        - php: 7.1
          env: SYMFONY_VERSION=3.2.*
    allow_failures:
        - php: hhvm
        - php: nightly

notifications:
    email: false
